### ISSUE TITLE
To enable Security in the service and OAM layer

### ISSUE THREAD

**Issue by Ziabatcha** [openBackhaul/MultiDomainInventoryProxy#19]
To enable security , the following code in the index.js needs to be commented.
 
```
// uncomment if you do not want to validate security e.g. operation-key, basic auth, etc
appCommons.openApiValidatorOptions.validateSecurity = false;
```
 
Currently , this uncommented code makes the server to accept any operation-key / basic auth.

**Comment by MFMentopolis** [comment]
This issue is related to this open bug of the MicroWaveDeviceInventory:
https://github.com/openBackhaul/MicroWaveDeviceInventory/issues/829

As soon as security is enabled in MWDI, we can also enable it here in MDIP.

**Comment by kmohr-soprasteria** [comment]
I checked again the respective issues in MWDI repository and saw that Thorsten explained, that this is related to a bug in MWDI OAS, but rather needs to be solved by SIAE modifying the validation routine.

**Comment by paulBMentopolis** [comment]
This issue should already be resolved by the fix for https://github.com/openBackhaul/MultiDomainInventoryProxy/issues/31 and can be closed.

If the response-validation which is currently not active in MDIP will be activated in the future (when MWDI responses are valid against MDIP spec), a new issue can be opened.
