### ISSUE TITLE
Security must be enabled: Basic auth is not working

### ISSUE THREAD

**Issue by alattoch** [openBackhaul/MultiDomainInventoryProxy#31]
The MDIP should support Security basic auth Username and password should be evaluated
The Control Construct response should not be activated.

**Comment by MFMentopolis** [comment]
Hello, this issue is already handled in https://github.com/openBackhaul/MultiDomainInventoryProxy/issues/19 .

**Comment by paulBMentopolis** [comment]
The proposed solution for this issue by Iswaryaa did not work. But we found a way to make it work by deactivating only the validation of responses. This must be used to be able to use responses by MWDI as responses in MDIP, as MDIP works as a proxy for MWDI requests. MWDI responses are not valid against MDIP spec. Basic auth works now as expected.

Fixed in tag "v1.0.0_impl-fix-3".

Testcase:
When using normal validation, the service "/core-model-1-4:network-control-domain=cache/control-construct={mountName}" did always run into a validation error when returning data for devices from MWDI. Since the response is not validated anymore against spec, it is returned normally. There may be more services where this validation is relevant.

**Comment by IswaryaaS** [comment]
Hi @paulBMentopolis, I can see the validation of response has been disabled for solving CC response validation error. 
It seems there is a misunderstanding that my solution did not work because I could find the implemented solution in v1.0.0_impl-fix-3 is exactly the same as I provided through mail. 


![validateResponse](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/88484011/0bbc5801-e4e2-4078-a452-7cdaea05e500). 

However, I am happy that the issue has been resolved after the fix. Thanks.

**Comment by paulBMentopolis** [comment]
Hi @IswaryaaS , I checked again, you're correct, in the second part you also proposed the very same solution. In my comment I was referring to the first part (general disabling of the validation) which did not produce the desired results.

**Comment by IswaryaaS** [comment]
Hi @paulBMentopolis, In the first part, I mentioned about the current implementation of MDIP where validation is completely disabled which is not a proposal but to indicate the code causing actual problem. 

The second picture is the one which I actually proposed. The part which is present below "Solution" is the actual proposed temporary solution.

**Comment by Ziabatcha** [comment]
Tested okay with v1.0.0_impl-fix-5
Basic auth - authentication doesnt allow any Basic services. 
For Basic services need to authorize via op-key.

![image](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/150062735/93ad106f-7e31-4fa2-85cc-cca648725ae0)
![image](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/150062735/0c05f506-d97f-4a7e-bdc7-335fa488ecb1)

**Comment by alattoch** [comment]
HI Zia, are the Basic Service needed for the Client operation. Or will it just be needed for the Deployment the application?
Regards, Andreas

**Comment by Ziabatcha** [comment]
As per the discussion in call with Andreas, closing this issue. 
Issue got fixed in v1.0.0_impl-fix-5

**Comment by openBackhaul** [comment]
I tested consuming a convenience service with wrong BasicAuth and got blocked.

**Comment by openBackhaul** [comment]
Fixed.
