### ISSUE TITLE
Responses to out-of-MW-SDN-domain software have x-correlator header

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/MultiDomainInventoryProxy#47]
x-correlator header should not be sent on the interface towards the out-of-MW-SDN-domain software.

The following paths are affected:
- /v1/provide-list-of-connected-devices 
- /v1/provide-list-of-device-interfaces
- /v1/provide-list-of-actual-device-equipment
- ...
- /core-model-1-4:network-control-domain=cache/control-construct={mountName}

**Comment by paulBMentopolis** [comment]
Fixed in tag "v1.0.0_impl-fix-6".

![Screenshot 2024-04-09 145451](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/148756388/5389994a-432e-4586-9514-14355f1590f7)

![Screenshot 2024-04-09 145423](https://github.com/openBackhaul/MultiDomainInventoryProxy/assets/148756388/63433e28-9667-4d63-8167-89546f7fbcd0)

**Comment by openBackhaul** [comment]
Fixed.
